# ТОП-7 графиков для вашей презентации

In [ ]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

## 1. Загрузка и базовые преобразования данных
Источники данных:
- https://www.kaggle.com/datasets/unsdsn/world-happiness?resource=download&select=2019.csv
- https://www.kaggle.com/datasets/nelgiriyewithana/countries-of-the-world-2023

In [ ]:
data1 = pd.read_csv('2019.csv')
print(data1.shape)
data1.head(3)

(156, 9)

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341

In [ ]:
data2 = pd.read_csv('world-data-2023.csv')
print(data2.shape)
data2.head(3)

(195, 35)

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,Latitude,Longitude
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.49,93.0,Kabul,"8,672",...,78.40%,0.28,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",33.939110,67.709953
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",...,56.90%,1.20,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593",41.153332,20.168331
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.28,213.0,Algiers,"150,006",...,28.10%,1.72,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100",28.033886,1.659626

In [ ]:
data = data1.merge(
    data2[['Official language', 'Country', 'Land Area(Km2)', 'Density\n(P/Km2)', 'Total tax rate', 'Unemployment rate', 'Population', 'Urban_population']],
    left_on='Country or region',
    right_on='Country',
    how='inner'
).drop('Country', axis=1)

In [ ]:
data['Land Area(Km2)'] = data['Land Area(Km2)'].str.replace(',', '').astype(float)
data['Population'] = data['Population'].str.replace(',', '').astype(int)
data['Urban_population'] = data['Urban_population'].str.replace(',', '').astype(float)

data['Total tax rate'] = data['Total tax rate'].str.replace('%', '').astype(float)
data['Unemployment rate'] = data['Unemployment rate'].str.replace('%', '').astype(float)

data['Density\n(P/Km2)'] = data['Density\n(P/Km2)'].str.replace(',', '').astype(int)

data.head()

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Official language,Land Area(Km2),Density\n(P/Km2),Total tax rate,Unemployment rate,Population,Urban_population
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393,Swedish,338145.0,18,36.6,6.59,5520314,4716888.0
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410,Danish,43094.0,137,23.8,4.91,5818553,5119978.0
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341,Norwegian,323802.0,15,36.2,3.35,5347896,4418218.0
3,4,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118,Icelandic,103000.0,3,31.9,2.84,361313,339110.0
4,5,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298,Dutch,41543.0,508,41.2,3.20,17332850,15924729.0

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145 entries, 0 to 144
Data columns (total 16 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Overall rank                  145 non-null    int64
 1   Country or region             145 non-null    object
 2   Score                         145 non-null    float64
 3   GDP per capita                145 non-null    float64
 4   Social support                145 non-null    float64
 5   Healthy life expectancy       145 non-null    float64
 6   Freedom to make life choices  145 non-null    float64
 7   Generosity                    145 non-null    float64
 8   Perceptions of corruption     145 non-null    float64
 9   Official language             141 non-null    object
 10  Land Area(Km2)                145 non-null    float64
 11  Density
(P/Km2)               145 non-null    int64
 12  Total tax rate                142 non-null    float64
 13  Unemployment rate             144 non-null    float64
 14  Population                    145 non-null    int64
 15  Urban_population              144 non-null    float64
dtypes: float64(11), int64(3), object(2)
memory usage: 18.3+ KB

In [ ]:
# data[data['Country'].isnull()]['Country or region']

In [ ]:
data.describe()

,Overall rank,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Land Area(Km2),Density\n(P/Km2),Total tax rate,Unemployment rate,Population,Urban_population
count,145.000000,145.000000,145.000000,145.000000,145.000000,145.000000,145.000000,145.000000,1.450000e+02,145.000000,142.000000,144.000000,1.450000e+02,1.440000e+02
mean,78.517241,5.406524,0.903303,1.207552,0.728448,0.392952,0.183703,0.109393,8.701256e+05,212.600000,41.325352,6.767292,5.097019e+07,2.858275e+07
std,45.483071,1.127660,0.394192,0.304771,0.234457,0.146577,0.096667,0.094358,2.179577e+06,729.483297,21.555702,5.092444,1.661611e+08,8.567576e+07
min,1.000000,2.853000,0.000000,0.000000,0.105000,0.000000,0.000000,0.000000,3.160000e+02,2.000000,9.900000,0.090000,3.613130e+05,2.481520e+05
25%,40.000000,4.548000,0.578000,1.055000,0.555000,0.305000,0.109000,0.047000,6.530000e+04,32.000000,30.725000,3.395000,5.454073e+06,2.920335e+06
50%,79.000000,5.373000,0.960000,1.293000,0.795000,0.418000,0.176000,0.085000,2.410380e+05,83.000000,37.800000,5.190000,1.169472e+07,7.017222e+06
75%,117.000000,6.182000,1.221000,1.454000,0.881000,0.508000,0.246000,0.140000,6.522300e+05,152.000000,48.100000,8.915000,3.699198e+07,2.284119e+07
max,156.000000,7.769000,1.684000,1.624000,1.141000,0.631000,0.566000,0.453000,1.709824e+07,8358.000000,219.600000,28.180000,1.397715e+09,8.429340e+08

In [ ]:
data.describe(include='object')

       Country or region Official language
count                145               141
unique               145                66
top              Finland            French
freq                   1                19

In [ ]:
data.dropna(inplace=True)

## 2. Подготовка

In [ ]:
# группировка официальных языков (6 самых частых)
top_languages = data['Official language'].value_counts().nlargest(6).index.tolist()
data['Language_group'] = data['Official language'].map(
   lambda x: x if x in top_languages else 'Other'
)
# создаем категории уровней - понадобится для многих графиков
# сначала выделим те, для которых нужны отдельные правила
data['Freedom_level'] = pd.qcut(data['Freedom to make life choices'], q=5, labels=['Super low', 'Low', 'Medium', 'High', 'Super high'])
data['Corruption_level'] = pd.qcut(data['Perceptions of corruption'], q=3, labels=['High corrup', 'Medium corrup', 'Low corrup'])

# соответствие для оставшихся с q=3
features = {
    'Healthy life expectancy': ('Healthy_life_level', 'HL'),
    'Total tax rate': ('Total_tax_rate_level', 'TR'),
    'Score': ('Happiness_level', 'Score'),
    'Generosity': ('Generosity_level', 'GR'),
    'Unemployment rate': ('Unemployment_rate_level', 'Unempl'),
}

for col, (new_col, suffix) in features.items():
    labels = [f'Low {suffix}', f'Medium {suffix}', f'High {suffix}']
    data[new_col] = pd.qcut(data[col], q=3, labels=labels)

## Bubble chart

Без раскраски

In [ ]:
fig = px.scatter(
   data,
   x="GDP per capita",
   y="Score",
   size="Population",
  #  color="Language_group",
   hover_name="Country or region",
   size_max=60,
   title="GDP vs Happiness, size=population"
)
# подписи осей
fig.update_layout(
   xaxis_title="GDP per capita",
   yaxis_title="Happiness Score"
)
fig.show()

С раскраской

In [ ]:
fig = px.scatter(
   data,
   x="GDP per capita",
   y="Score",
   size="Population",
   color="Language_group",
   hover_name="Country or region",
   size_max=60,
   title="GDP vs Happiness, size=population, color=language"
)
# подписи осей
fig.update_layout(
   xaxis_title="GDP per capita",
   yaxis_title="Happiness Score"
)
fig.show()

Есть линейная связь ВВП на душу и уровня счастья. А численность населения и официальный язык как будто не особо влияют.

## Treemap

In [ ]:
fig = px.treemap(
   data,
   path=["Country or region"],
   values="Density\n(P/Km2)",
   color="Score",
   color_continuous_scale="Viridis",
   title="Density & score by countries"
)
fig.show()

In [ ]:
fig = px.treemap(
   data,
   path=["Happiness_level", "Country or region"],
   values="Density\n(P/Km2)",
   color="Score",
   color_continuous_scale="Viridis",
   title="Density & score by countries"
)
fig.show()

/usr/local/lib/python3.12/dist-packages/plotly/express/_core.py:1727: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

/usr/local/lib/python3.12/dist-packages/plotly/express/_core.py:1727: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

Наглядно видим страны с самой высокой плотностью, но не сказать, что есть четкая связь плотности населения и счастья... Среди маленьких и больших лоскутков видим как ярко-жёлтые, так и темно-синие раскраски.

## Heatmap

In [ ]:
pivot = data.pivot_table(
   index="Healthy_life_level",
   columns="Freedom_level",
   values="Score",
   aggfunc="mean"
)

fig = px.imshow(
   pivot,
   text_auto=True,
   color_continuous_scale="Blues",
   title="Mean Score on Healthy life expectancy & Freedom to make life choices"
)
fig.show()

/tmp/ipython-input-1296238477.py:1: FutureWarning:

The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior

Обнаружена ещё одна зависимость! На уровень счастья влияет ожидаемая продолжительность здоровой жизни и оценка свободы!

## 4. Sankey

In [ ]:
# агрегация потоков
sankey_data = (
   data
   .groupby(
       ['Happiness_level', 'Total_tax_rate_level', 'Generosity_level']
   )
   .size()
   .reset_index(name='count')
)

# список уникальных узлов
labels = list(
   pd.concat([
        sankey_data['Happiness_level'],
        sankey_data['Total_tax_rate_level'],
        sankey_data['Generosity_level']
   ]).unique()
)
label_to_idx = {label: i for i, label in enumerate(labels)}

# 1-я половина
source = sankey_data['Happiness_level'].map(label_to_idx)
target = sankey_data['Generosity_level'].map(label_to_idx)
value = sankey_data['count']

# 2-я половина
source2 = sankey_data['Generosity_level'].map(label_to_idx)
target2 = sankey_data['Total_tax_rate_level'].map(label_to_idx)
value2 = sankey_data['count']

# объединяем
sources = pd.concat([source, source2])
targets = pd.concat([target, target2])
values = pd.concat([value, value2])

/tmp/ipython-input-1693691937.py:4: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

In [ ]:
fig = go.Figure(data=[go.Sankey(
   node=dict(
       pad=15,
       thickness=20,
       line=dict(color="black", width=0.5),
       label=labels
   ),
   link=dict(
       source=sources,
       target=targets,
       value=values
   )
)])
fig.update_layout(title_text="Happiness -> Generosity -> Total_tax_rate", font_size=10)
fig.show()

## Sunburst

In [ ]:
fig = px.sunburst(
   data,
   path=['Corruption_level', 'Unemployment_rate_level'],
   values='Score',
   color='Score',
   color_continuous_scale='Viridis',
   title="Happiness: Corruption -> Unemployment"
)
fig.show()

/usr/local/lib/python3.12/dist-packages/plotly/express/_core.py:1727: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

/usr/local/lib/python3.12/dist-packages/plotly/express/_core.py:1727: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

In [ ]:
fig = px.sunburst(
    data,
    path=['Corruption_level', 'Unemployment_rate_level'],
    values='Score',
    color='Score',
    color_continuous_scale='RdYlGn',   # более контрастная шкала
    title="Happiness: Corruption -> Unemployment"
)

fig.update_traces(
    textinfo="label+percent entry",   # подписи + доли
    insidetextorientation="radial",
    marker=dict(
        line=dict(color="white", width=2)  # границы сегментов
    ),
    hovertemplate=(
        "<b>%{label}</b><br>"
        "Score: %{value:.2f}<br>"
        "Share: %{percentEntry:.1%}<extra></extra>"
    )
)

fig.update_layout(
    title_font_size=22,
    title_x=0.5,
    font=dict(family="Arial", size=12),
    margin=dict(t=80, l=20, r=20, b=20),
    paper_bgcolor="#F9F9F9",   # фон всей области
    plot_bgcolor="#F9F9F9",
    coloraxis_colorbar=dict(
        title="Score",
        tickfont=dict(size=10)
    )
)

fig.show()

/usr/local/lib/python3.12/dist-packages/plotly/express/_core.py:1727: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

/usr/local/lib/python3.12/dist-packages/plotly/express/_core.py:1727: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

## Radar chart

In [ ]:
categories = [
   "GDP per capita", "Social support", "Healthy life expectancy",
   "Freedom to make life choices", "Generosity", "Perceptions of corruption"
]
radar_data = data.groupby("Happiness_level")[categories].mean().reset_index()

/tmp/ipython-input-392259809.py:5: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

In [ ]:
# from sklearn.preprocessing import MinMaxScaler

# scaler = MinMaxScaler()
# radar_data[categories] = scaler.fit_transform(
#     radar_data[categories]
# )

In [ ]:
fig = go.Figure()

for i, row in radar_data.iterrows():
   fig.add_trace(go.Scatterpolar(
       r=row[categories].values,
       theta=categories,
       fill='toself',
       name=row["Happiness_level"]
   ))
fig.update_layout(
   polar=dict(
       radialaxis=dict(visible=True)
   ),
   title="Average Factors by Happiness Level"
)
fig.show()

## 7. Choropleth

In [ ]:
fig = px.choropleth(
   data,
   locations="Country or region",  # или "iso_alpha" если есть
   locationmode="country names",   # "ISO-3" если используем ISO коды
   color="Score",
   hover_name="Country or region",
   color_continuous_scale=px.colors.sequential.Viridis,
   title="World Happiness Score by Country"
)
fig.show()

## 3D scatter*

In [ ]:
data['Urban_rate'] = data['Urban_population'] / data['Population']

In [ ]:
# Визуализируем зависимость GDP, Score и Healthy life expectancy
# Цвет = уровень счастья, размер = Population

fig9 = px.scatter_3d(
    data,
    x="GDP per capita",
    y="Unemployment rate",
    z="Urban_rate",
    color="Happiness_level",
    # size="Population",
    hover_name="Country or region",
    size_max=60,
    title="3D Scatter: GDP vs Happiness vs Life Expectancy"
)
fig9.update_layout(scene=dict(
    xaxis_title='GDP per capita',
    yaxis_title='Unemployment rate',
    zaxis_title='Urban rate'
))
fig9.show()